WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Models/BeerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AspNetCoreDemo.Web.Models
{
    public class BeerViewModel : BeerWebModel
    {
        public SelectList Breweries { get; set; }
    }
}

WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Controllers/BeersController.cs
using AspNetCoreDemo.Services.Exceptions;
using AspNetCoreDemo.Services.Services;
using AspNetCoreDemo.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AspNetCoreDemo.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService beerService;
        private readonly ModelMapper modelMapper;

        public BeersController(IBeerService beerService, ModelMapper modelMapper)
        {
            this.beerService = beerService;
            this.modelMapper = modelMapper;
        }

        //GET: /beers
        public IActionResult Index()
        {
            var beers = this.beerService.GetAll();

            return this.View(beers);
        }

        //GET: /beers/details/:id
        public IActionResult Details(int id)
        {
            try
            {
                var beer = this.beerService.Get(id);

                return this.View(beer);
            }
            catch (EntityNotFoundException)
            {
                return this.BeerNotFound(id);

                // Use default page
                //return this.NotFound();
            }
        }

        //GET: /beers/create
        public IActionResult Create()
        {
            var newBeerViewModel = new BeerViewModel();

            return this.BeerView(newBeerViewModel);
        }

        //POST: /beers/create
        [HttpPost]
        public IActionResult Create([Bind("Name,Abv,BreweryId")] BeerViewModel beerViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BeerView(beerViewModel);
            }

            var beer = this.modelMapper.ToModel(beerViewModel);
            this.beerService.Create(beer);

            return this.RedirectToAction(nameof(this.Index));
        }


        //GET: /beers/edit/:id
        public IActionResult Edit(int id)
        {
            try
            {
                var beer = this.beerService.Get(id);
                var beerViewModel = this.modelMapper.ToViewModel(beer);

                return this.BeerView(beerViewModel);
            }
            catch (EntityNotFoundException)
            {
                return this.BeerNotFound(id);
            }
        }

        //POST: /beers/edit/:id
        [HttpPost]
        public IActionResult Edit(int id, [Bind("Name,Abv,BreweryId")] BeerViewModel beerViewModel)
        {
            if (!ModelState.IsValid)
            {
                return this.BeerView(beerViewModel);
            }

            try
            {
                var beer = this.modelMapper.ToModel(beerViewModel);
                this.beerService.Update(id, beer);
            }
            catch (EntityNotFoundException)
            {
                return this.BeerNotFound(id);
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        //GET: /beers/delete/:id
        public IActionResult Delete(int id)
        {
            try
            {
                var beer = this.beerService.Get(id);

                return this.View(beer);
            }
            catch (EntityNotFoundException)
            {
                return this.BeerNotFound(id);
            }
        }

        //POST: /beers/delete/:id
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                this.beerService.Delete(id);
            }
            catch (EntityNotFoundException)
            {
                return this.BeerNotFound(id);
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        private IActionResult BeerNotFound(int id)
        {
            this.Response.StatusCode = StatusCodes.Status404NotFound;
            this.ViewData["error"] = $"Beer with id {id} does not exist.";
            return this.View("Error");
        }

        private IActionResult BeerView(BeerViewModel beerViewModel)
        {
            beerViewModel.Breweries = this.GetBreweries();
            return this.View(beerViewModel);
        }

        private SelectList GetBreweries()
        {
            var breweries = this.beerService.GetBreweries();
            return new SelectList(breweries, "Id", "Name");
        }
    }
}

WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Views/Beers/Create.cshtml
@model AspNetCoreDemo.Web.Models.BeerViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BeerTag Create Beer</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index" class="nav">Home</a>
                | <a asp-controller="Beers" asp-action="Index" class="nav">Beers</a>
                | <a asp-controller="Home" asp-action="About" class="nav">About</a>
            </h3>
        </div>
    </header>

    <div class="body-content">
        <h2>Create Beer</h2>

        <form asp-action="Create">
            <div>
                <label asp-for="Name" class="form-label"></label>
                <br />
                <input asp-for="Name" class="form-input" />
                <span asp-validation-for="Name" class="form-error"></span>
            </div>
            <div>
                <label asp-for="Abv" class="form-label"></label>
                <br />
                <input asp-for="Abv" class="form-input" />
                <span asp-validation-for="Abv" class="form-error"></span>
            </div>
            <div>
                <label class="form-label">Brewery</label>
                <br />
                <select asp-for="BreweryId" asp-items="Model.Breweries" class="form-input"></select>
                <span asp-validation-for="BreweryId"></span>
            </div>
            <div>
                <input type="submit" value="Create" class="btn-primary" />
                | <a asp-action="Index" class="nav">Back</a>
            </div>
        </form>
    </div>

    <footer>
        <div>
            <p>
                &copy; @DateTime.Now.Year - BeerTag - <a asp-controller="Home" asp-action="About">About</a>
            </p>
        </div>
    </footer>
</body>
</html>

WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Views/Beers/Delete.cshtml
@model AspNetCoreDemo.Data.Models.Beer
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BeerTag Delete Beer</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index" class="nav">Home</a>
                | <a asp-controller="Beers" asp-action="Index" class="nav">Beers</a>
                | <a asp-controller="Home" asp-action="About" class="nav">About</a>
            </h3>
        </div>
    </header>

    <div class="body-content">
        <h2>Delete @this.Model.Name</h2>

        <div>
            <h3>Are you sure you want to delete @this.Model.Name?</h3>
            <ul>
                <li class="margin12">Alc%: @this.Model.Abv</li>
                <li class="margin12">Brewery: @this.Model.Brewery.Name</li>
            </ul>
        </div>

        <form asp-action="Delete">
            <input type="submit" value="Delete" class="btn-danger" />
            | <a asp-action="Index" class="nav">Back</a>
        </form>
    </div>

    <footer>
        <div>
            <p>
                &copy; @DateTime.Now.Year - BeerTag - <a asp-controller="Home" asp-action="About">About</a>
            </p>
        </div>
    </footer>
</body>
</html>

WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Views/Beers/Details.cshtml
@model AspNetCoreDemo.Data.Models.Beer
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BeerTag Beer Details</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index" class="nav">Home</a>
                | <a asp-controller="Beers" asp-action="Index" class="nav">Beers</a>
                | <a asp-controller="Home" asp-action="About" class="nav">About</a>
            </h3>
        </div>
    </header>

    <div class="body-content">
        <h2>@this.Model.Name Details</h2>

        <div>
            <ul>
                <li class="margin12">Alc%: @this.Model.Abv</li>
                <li class="margin12">Brewery: @this.Model.Brewery.Name</li>
            </ul>
        </div>

        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id" class="nav">Edit</a>
            | <a asp-action="Index" class="nav">Back</a>
        </div>
    </div>

    <footer>
        <div>
            <p>
                &copy; @DateTime.Now.Year - BeerTag - <a asp-controller="Home" asp-action="About">About</a>
            </p>
        </div>
    </footer>
</body>
</html>

WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Views/Beers/Edit.cshtml
@model AspNetCoreDemo.Web.Models.BeerViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BeerTag Edit Beer</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index" class="nav">Home</a>
                | <a asp-controller="Beers" asp-action="Index" class="nav">Beers</a>
                | <a asp-controller="Home" asp-action="About" class="nav">About</a>
            </h3>
        </div>
    </header>

    <div class="body-content">
        <h2>Edit @this.Model.Name</h2>

        <form asp-action="Edit">
            <div>
                <label asp-for="Name" class="form-label"></label>
                <br />
                <input asp-for="Name" class="form-input" />
                <span asp-validation-for="Name" class="form-error"></span>
            </div>
            <div>
                <label asp-for="Abv" class="form-label"></label>
                <br />
                <input asp-for="Abv" class="form-input" />
                <span asp-validation-for="Abv" class="form-error"></span>
            </div>
            <div>
                <label class="form-label">Brewery</label>
                <br />
                <select asp-for="BreweryId" asp-items="Model.Breweries" class="form-input"></select>
                <span asp-validation-for="BreweryId"></span>
            </div>
            <div>
                <input type="submit" value="Save" class="btn-primary" />
                | <a asp-action="Index" class="nav">Back</a>
            </div>
        </form>
    </div>

    <footer>
        <div>
            <p>
                &copy; @DateTime.Now.Year - BeerTag - <a asp-controller="Home" asp-action="About">About</a>
            </p>
        </div>
    </footer>
</body>
</html>

WEB/12. ASP.NET Core MVC Forms and Data/Demo/AspNetCoreDemo.Web/Views/Beers/Index.cshtml
@model IEnumerable<AspNetCoreDemo.Data.Models.Beer>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BeerTag All Beers</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index" class="nav">Home</a>
                | <a asp-controller="Beers" asp-action="Index" class="nav">Beers</a>
                | <a asp-controller="Home" asp-action="About" class="nav">About</a>
            </h3>
        </div>
    </header>

    <div class="body-content">
        <h2>All Beers</h2>

        <p>
            <a asp-action="Create">Create New</a>
        </p>

        <div class="table">
            <div class="header">
                <div class="header-cell">Name</div>
                <div class="header-cell">ABV</div>
                <div class="header-cell">Brewery</div>
                <div class="header-cell">Actions</div>
            </div>

            @{
                foreach (var beer in this.Model)
                {
                    <div class="row">
                        <div class="cell">@beer.Name</div>
                        <div class="cell">@beer.Abv</div>
                        <div class="cell">@beer.Brewery.Name</div>
                        <div class="cell">
                            <a asp-action="Details" asp-route-id="@beer.Id" class="nav">Details</a>
                            | <a asp-action="Edit" asp-route-id="@beer.Id" class="nav">Edit</a>
                            | <a asp-action="Delete" asp-route-id="@beer.Id" class="nav">Delete</a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>

    <footer>
        <div>
            <p>
                &copy; @DateTime.Now.Year - BeerTag - <a asp-controller="Home" asp-action="About">About</a>
            </p>
        </div>
    </footer>
</body>
</html>